---
registry:
  name: dev
  url: {{APPS_URL}}
  user: uuu
  pass: ppp
  org: ansibleapp
dao:
  etcd_host: etcd
  etcd_port: 2379
log:
  logfile: /var/log/ansible-service-broker.log
  stdout: true
  level: debug
  color: true
openshift:
  target: {{OPENSHIFT_TARGET}}
  user: {{OPENSHIFT_USER}}
  pass: {{OPENSHIFT_PASS}}
